"""
Textos de la interfaz en varios idiomas.

Cada texto tiene una CLAVE estable; el codigo nunca escribe texto suelto, pide
la clave. Anadir un idioma es anadir un diccionario aqui: si le falta alguna
clave, se usa el espanol como respaldo en vez de romper la ventana.
"""

from __future__ import annotations

IDIOMAS = [("es", "Espanol"), ("en", "English")]
POR_DEFECTO = "es"

TEXTOS: dict[str, dict[str, str]] = {
    "es": {
        # --- Ventana principal ---
        "titulo": "Gestos · Control por camara",
        "app_titulo": "Control por gestos",
        "app_sub": "mueve el cursor con la mano",
        "sec_gestos": "GESTOS  ·  ELIGE QUE HACE CADA MANO",
        "sec_puntero": "PUNTERO",
        "sec_camara": "CAMARA",
        "sec_ayuda": "MIENTRAS DETECTA",
        "velocidad": "Velocidad",
        "velocidad_pista": "lento y preciso ←→ rapido",
        "aceleracion": "Aceleracion",
        "aceleracion_pista": "empuje extra en gestos amplios",
        "compartir_camara": "Compartir con otras apps (Zoom, Teams…)",
        "preguntar_camara": "Preguntar que camara usar al arrancar",
        "ayuda_deteccion": ("La ventana de camara lleva un panel con el estado.\n"
                            "Salir de la deteccion:  tecla  Q  o cerrar la ventana.\n"
                            "Tecla  H:  esconder o mostrar ese panel.\n"
                            "El gesto de on/off pausa el control sin cerrar nada."),
        "pista_gestos": ("Despliega para elegir raton o un atajo ya hecho.   "
                         "⌨ graba la combinacion\nde teclas que quieras "
                         "(incluida la tecla Windows).   ✕ deja el gesto sin "
                         "asignar."),
        "iniciar": "▶  Iniciar",
        "detener": "■  Detener",
        "guardar": "Guardar",
        "restablecer": "Restablecer",
        "ajustes": "⚙  Ajustes",
        "tema_claro": "☀  Claro",
        "tema_oscuro": "🌙  Oscuro",
        # --- Estados ---
        "estado_detenido": "Detenido",
        "estado_marcha": "En marcha · ponte frente a la camara",
        "estado_cerrado": "La deteccion se cerro",
        "estado_guardado": "Configuracion guardada",
        "estado_fabrica": "Valores de fabrica (sin guardar)",
        "estado_pulsa": "Pulsa las teclas…",
        "estado_cancelado": "Grabacion cancelada",
        "estado_sin_teclado": "No se pudo capturar el teclado en este equipo",
        "estado_sin_asignar": "{gesto} sin asignar",
        # --- Ajustes ---
        "ajustes_titulo": "Ajustes",
        "aj_general": "General",
        "aj_idioma": "Idioma",
        "aj_tema": "Tema",
        "aj_inicio": "Iniciar con Windows",
        "aj_inicio_pista": "La aplicacion se abrira sola al encender el equipo",
        "aj_minimizado": "Arrancar minimizado en la bandeja",
        "aj_autodeteccion": "Empezar a detectar al abrir",
        "aj_confirmar": "Preguntar antes de cerrar",
        "aj_deteccion": "Deteccion",
        "aj_espejo": "Ver la camara en espejo",
        "aj_estela": "Dibujar la estela del dedo",
        "aj_ventana": "Mostrar la ventana de la camara",
        "aj_vista": "Ver la camara en la ventana principal",
        "aj_vista_pista": "Vista previa para encuadrarte antes de empezar",
        "aj_hud": "Panel de estado sobre la camara",
        "aj_hud_pista": "Gestos, medidores y fps; se quita con la tecla H",
        "aj_resolucion": "Resolucion de captura",
        "aj_tiempos": "Tiempos",
        "aj_espera_atajo": "Mantener para lanzar un atajo (s)",
        "aj_espera_control": "Mantener para activar/desactivar (s)",
        "aj_avisos": "Avisos",
        "aj_sonido": "Sonido al hacer clic o lanzar un atajo",
        "aj_ayuda": "Ayuda",
        "aj_github": "🌐  Abrir el proyecto en GitHub",
        "aj_manual": "📖  Ver la guia de gestos",
        "aj_carpeta": "📁  Abrir la carpeta de configuracion",
        "aj_version": "Version {v}",
        "cerrar": "Cerrar",
        "aceptar": "Aceptar",
        "cancelar": "Cancelar",
        "confirmar_salir": "¿Cerrar la aplicacion?",
        # --- Instalador ---
        "inst_titulo": "Instalar Control por gestos",
        "inst_bienvenida": "Bienvenido",
        "inst_intro": ("Este asistente instalara Control por gestos en tu "
                       "equipo.\nElige donde quieres instalarlo y pulsa "
                       "Instalar."),
        "inst_carpeta": "Carpeta de instalacion",
        "inst_examinar": "Examinar…",
        "inst_idioma": "Idioma de la aplicacion",
        "inst_acceso": "Crear acceso directo en el Escritorio",
        "inst_menu": "Anadir al menu Inicio",
        "inst_autoarranque": "Iniciar con Windows",
        "inst_abrir": "Abrir la aplicacion al terminar",
        "inst_instalar": "Instalar",
        "inst_instalando": "Instalando…",
        "inst_listo": "Instalacion completada",
        "inst_error": "No se pudo instalar: {e}",
        "inst_espacio": "Se necesitan unos {mb} MB",
        # --- Formas de la mano ---
        "forma_un_dedo": "1 dedo  ·  indice",
        "forma_dos_dedos": "2 dedos  ·  + medio",
        "forma_tres_dedos": "3 dedos  ·  + anular",
        "forma_pulgar": "Pulgar arriba",
        "forma_mano_abierta": "Mano abierta  ·  5 dedos",
        "forma_puno": "Puno  ·  0 dedos",
        "forma_pulgar_menique": "Pulgar + menique",
        # --- Grupos del menu ---
        "grupo_raton": "Raton y control",
        "grupo_ventanas": "Ventanas",
        "grupo_cambiar": "Cambiar de aplicacion",
        "grupo_sistema": "Sistema",
        "grupo_edicion": "Edicion",
        "grupo_multimedia": "Multimedia",
        "grupo_navegador": "Navegador",
        "grupo_propios": "Mis atajos",
        # --- Acciones ---
        "accion_mover": "Mover el cursor",
        "accion_clic_izq": "Clic izquierdo / arrastrar",
        "accion_clic_der": "Clic derecho",
        "accion_alternar": "Activar / desactivar",
        "accion_nada": "Nada",
        "accion_maximizar": "Maximizar ventana",
        "accion_minimizar": "Minimizar ventana",
        "accion_acoplar_izq": "Acoplar a la izquierda",
        "accion_acoplar_der": "Acoplar a la derecha",
        "accion_cerrar_app": "Cerrar ventana",
        "accion_pantalla_completa": "Pantalla completa",
        "accion_cambiar_app": "Cambiar de aplicacion",
        "accion_vista_tareas": "Vista de tareas",
        "accion_escritorio": "Mostrar el escritorio",
        "accion_escritorio_der": "Escritorio siguiente",
        "accion_escritorio_izq": "Escritorio anterior",
        "accion_explorador": "Abrir el Explorador",
        "accion_ajustes": "Abrir Configuracion",
        "accion_buscar": "Buscar en Windows",
        "accion_bloquear": "Bloquear el equipo",
        "accion_captura": "Recorte de pantalla",
        "accion_emoji": "Panel de emoji",
        "accion_copiar": "Copiar",
        "accion_pegar": "Pegar",
        "accion_deshacer": "Deshacer",
        "accion_rehacer": "Rehacer",
        "accion_seleccionar": "Seleccionar todo",
        "accion_guardar_doc": "Guardar",
        "accion_vol_subir": "Subir volumen",
        "accion_vol_bajar": "Bajar volumen",
        "accion_silencio": "Silenciar",
        "accion_play": "Reproducir / pausar",
        "accion_siguiente": "Pista siguiente",
        "accion_anterior": "Pista anterior",
        "accion_pestana_nueva": "Pestana nueva",
        "accion_cerrar_pestana": "Cerrar pestana",
        "accion_recargar": "Recargar",
        # --- HUD de la ventana de camara ---
        # Se dibujan con la fuente Hershey de OpenCV, que no tiene acentos ni
        # simbolos: se escriben ya en ASCII y en corto, porque van en tiras de
        # 20 px y en columnas de 40 px que no dan para mas.
        "hud_activo": "CONTROL ACTIVO",
        "hud_pausa": "EN PAUSA",
        "hud_arrastre": "ARRASTRANDO",
        "hud_gestos": "GESTOS",
        "hud_puntero": "PUNTERO",
        "hud_vel": "VEL",
        "hud_senal": "SENAL",
        "hud_ganancia": "VELOCIDAD",
        "hud_perdidos": "PERDIDOS",
        "hud_teclas": "Q salir - C on/off - H panel",
        # --- Vista previa de la ventana principal ---
        "vista_titulo": "VISTA PREVIA",
        "vista_parada": "Vista previa apagada",
        "vista_esperando": "Abriendo la camara…",
        "vista_sin_camara": "No se pudo abrir la camara",
    },
    "en": {
        "titulo": "Gestures · Camera control",
        "app_titulo": "Gesture control",
        "app_sub": "move the cursor with your hand",
        "sec_gestos": "GESTURES  ·  CHOOSE WHAT EACH HAND DOES",
        "sec_puntero": "POINTER",
        "sec_camara": "CAMERA",
        "sec_ayuda": "WHILE DETECTING",
        "velocidad": "Speed",
        "velocidad_pista": "slow and precise ←→ fast",
        "aceleracion": "Acceleration",
        "aceleracion_pista": "extra push on wide gestures",
        "compartir_camara": "Share with other apps (Zoom, Teams…)",
        "preguntar_camara": "Ask which camera to use on startup",
        "ayuda_deteccion": ("The camera window has a status panel on it.\n"
                            "Quit detection:  press  Q  or close the window.\n"
                            "Press  H:  hide or show that panel.\n"
                            "The on/off gesture pauses control without closing."),
        "pista_gestos": ("Open the list to pick a mouse action or a ready-made "
                         "shortcut.   ⌨ records any\nkey combination (the "
                         "Windows key included).   ✕ clears the gesture."),
        "iniciar": "▶  Start",
        "detener": "■  Stop",
        "guardar": "Save",
        "restablecer": "Reset",
        "ajustes": "⚙  Settings",
        "tema_claro": "☀  Light",
        "tema_oscuro": "🌙  Dark",
        "estado_detenido": "Stopped",
        "estado_marcha": "Running · stand in front of the camera",
        "estado_cerrado": "Detection closed",
        "estado_guardado": "Settings saved",
        "estado_fabrica": "Factory defaults (not saved)",
        "estado_pulsa": "Press the keys…",
        "estado_cancelado": "Recording cancelled",
        "estado_sin_teclado": "Could not capture the keyboard on this machine",
        "estado_sin_asignar": "{gesto} unassigned",
        "ajustes_titulo": "Settings",
        "aj_general": "General",
        "aj_idioma": "Language",
        "aj_tema": "Theme",
        "aj_inicio": "Start with Windows",
        "aj_inicio_pista": "The app will open by itself when you turn the PC on",
        "aj_minimizado": "Start minimised to the tray",
        "aj_autodeteccion": "Start detecting on launch",
        "aj_confirmar": "Ask before closing",
        "aj_deteccion": "Detection",
        "aj_espejo": "Mirror the camera view",
        "aj_estela": "Draw the finger trail",
        "aj_ventana": "Show the camera window",
        "aj_vista": "Show the camera in the main window",
        "aj_vista_pista": "Preview to frame yourself before you start",
        "aj_hud": "Status panel over the camera",
        "aj_hud_pista": "Gestures, meters and fps; press H to hide it",
        "aj_resolucion": "Capture resolution",
        "aj_tiempos": "Timings",
        "aj_espera_atajo": "Hold to fire a shortcut (s)",
        "aj_espera_control": "Hold to enable/disable (s)",
        "aj_avisos": "Feedback",
        "aj_sonido": "Sound on click or shortcut",
        "aj_ayuda": "Help",
        "aj_github": "🌐  Open the project on GitHub",
        "aj_manual": "📖  See the gesture guide",
        "aj_carpeta": "📁  Open the settings folder",
        "aj_version": "Version {v}",
        "cerrar": "Close",
        "aceptar": "OK",
        "cancelar": "Cancel",
        "confirmar_salir": "Close the application?",
        "inst_titulo": "Install Gesture Control",
        "inst_bienvenida": "Welcome",
        "inst_intro": ("This wizard will install Gesture Control on your "
                       "computer.\nChoose where to install it and press "
                       "Install."),
        "inst_carpeta": "Installation folder",
        "inst_examinar": "Browse…",
        "inst_idioma": "Application language",
        "inst_acceso": "Create a Desktop shortcut",
        "inst_menu": "Add to the Start menu",
        "inst_autoarranque": "Start with Windows",
        "inst_abrir": "Open the app when finished",
        "inst_instalar": "Install",
        "inst_instalando": "Installing…",
        "inst_listo": "Installation complete",
        "inst_error": "Could not install: {e}",
        "inst_espacio": "About {mb} MB needed",
        # --- Hand shapes ---
        "forma_un_dedo": "1 finger  ·  index",
        "forma_dos_dedos": "2 fingers  ·  + middle",
        "forma_tres_dedos": "3 fingers  ·  + ring",
        "forma_pulgar": "Thumbs up",
        "forma_mano_abierta": "Open hand  ·  5 fingers",
        "forma_puno": "Fist  ·  0 fingers",
        "forma_pulgar_menique": "Thumb + little finger",
        # --- Menu groups ---
        "grupo_raton": "Mouse and control",
        "grupo_ventanas": "Windows",
        "grupo_cambiar": "Switch application",
        "grupo_sistema": "System",
        "grupo_edicion": "Editing",
        "grupo_multimedia": "Media",
        "grupo_navegador": "Browser",
        "grupo_propios": "My shortcuts",
        # --- Actions ---
        "accion_mover": "Move the cursor",
        "accion_clic_izq": "Left click / drag",
        "accion_clic_der": "Right click",
        "accion_alternar": "Enable / disable",
        "accion_nada": "Nothing",
        "accion_maximizar": "Maximise window",
        "accion_minimizar": "Minimise window",
        "accion_acoplar_izq": "Snap left",
        "accion_acoplar_der": "Snap right",
        "accion_cerrar_app": "Close window",
        "accion_pantalla_completa": "Full screen",
        "accion_cambiar_app": "Switch application",
        "accion_vista_tareas": "Task view",
        "accion_escritorio": "Show the desktop",
        "accion_escritorio_der": "Next desktop",
        "accion_escritorio_izq": "Previous desktop",
        "accion_explorador": "Open File Explorer",
        "accion_ajustes": "Open Settings",
        "accion_buscar": "Search Windows",
        "accion_bloquear": "Lock the computer",
        "accion_captura": "Screen snip",
        "accion_emoji": "Emoji panel",
        "accion_copiar": "Copy",
        "accion_pegar": "Paste",
        "accion_deshacer": "Undo",
        "accion_rehacer": "Redo",
        "accion_seleccionar": "Select all",
        "accion_guardar_doc": "Save",
        "accion_vol_subir": "Volume up",
        "accion_vol_bajar": "Volume down",
        "accion_silencio": "Mute",
        "accion_play": "Play / pause",
        "accion_siguiente": "Next track",
        "accion_anterior": "Previous track",
        "accion_pestana_nueva": "New tab",
        "accion_cerrar_pestana": "Close tab",
        "accion_recargar": "Reload",
        # --- Camera window HUD (see the Spanish block) ---
        "hud_activo": "CONTROL ON",
        "hud_pausa": "PAUSED",
        "hud_arrastre": "DRAGGING",
        "hud_gestos": "GESTURES",
        "hud_puntero": "POINTER",
        "hud_vel": "SPD",
        "hud_senal": "SIGNAL",
        "hud_ganancia": "SPEED",
        "hud_perdidos": "DROPPED",
        "hud_teclas": "Q quit - C on/off - H panel",
        # --- Main window preview ---
        "vista_titulo": "PREVIEW",
        "vista_parada": "Preview off",
        "vista_esperando": "Opening the camera…",
        "vista_sin_camara": "Could not open the camera",
    },
}

URL_GITHUB = "https://github.com/swaazzyy/automatization-signs"
VERSION = "2.0"


class Textos:
    """Traductor: `t("clave")` devuelve el texto en el idioma elegido."""

    def __init__(self, idioma: str = POR_DEFECTO) -> None:
        self.cambiar(idioma)

    def cambiar(self, idioma: str) -> None:
        self.idioma = idioma if idioma in TEXTOS else POR_DEFECTO
        self._d = TEXTOS[self.idioma]
        self._respaldo = TEXTOS[POR_DEFECTO]

    def __call__(self, clave: str, **fmt) -> str:
        # Si a un idioma le falta una clave se usa el espanol: nunca se muestra
        # el identificador crudo ni salta una excepcion en mitad de la ventana.
        texto = self._d.get(clave) or self._respaldo.get(clave) or clave
        return texto.format(**fmt) if fmt else texto
